# Generated by Django 5.2 on 2025-04-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_name', models.CharField(max_length=255)),
                ('total_transactions', models.IntegerField()),
                ('missing_in_b', models.IntegerField()),
                ('missing_in_a', models.IntegerField()),
                ('amount_mismatches', models.IntegerField()),
                ('status_mismatches', models.IntegerField()),
                ('processing_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('discrepancy_type', models.CharField(max_length=50)),
                ('details', models.JSONField()),
                ('system_a_data', models.JSONField(blank=True, null=True)),
                ('system_b_data', models.JSONField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='home.reconciliationreport')),
            ],
            options={
                'indexes': [models.Index(fields=['transaction_id'], name='home_discre_transac_3fbd2e_idx'), models.Index(fields=['discrepancy_type'], name='home_discre_discrep_5e835c_idx')],
            },
        ),
    ]
