# Generated by Django 5.2 on 2025-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconciliationreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reconciliationreport',
            old_name='amount_mismatches',
            new_name='system_a_count',
        ),
        migrations.RenameField(
            model_name='reconciliationreport',
            old_name='missing_in_a',
            new_name='system_b_count',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='details',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='system_a_data',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='system_b_data',
        ),
        migrations.RemoveField(
            model_name='reconciliationreport',
            name='missing_in_b',
        ),
        migrations.RemoveField(
            model_name='reconciliationreport',
            name='report_name',
        ),
        migrations.RemoveField(
            model_name='reconciliationreport',
            name='status_mismatches',
        ),
        migrations.RemoveField(
            model_name='reconciliationreport',
            name='total_transactions',
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='amount_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='amount_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='status_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='status_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='discrepancy_type',
            field=models.CharField(choices=[('missing_in_b', 'Missing in System B'), ('missing_in_a', 'Missing in System A'), ('amount_mismatch', 'Amount Mismatch'), ('status_mismatch', 'Status Mismatch')], max_length=20),
        ),
    ]
