# Generated by Django 5.2 on 2025-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reconciliationreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_a_file', models.FileField(upload_to='csvs/')),
                ('source_b_file', models.FileField(upload_to='csvs/')),
                ('result', models.JSONField()),
            ],
        ),
    ]
