# Generated by Django 5.2 on 2025-04-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reconciledreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReconciledReport',
        ),
    ]
